/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIsIntrohubRouteImport } from './routes/what-is-introhub'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GetDemoRouteImport } from './routes/get-demo'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/_help'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as HelpTermsAndConditionsRouteImport } from './routes/_help/terms-and-conditions'
import { Route as HelpPrivacyPolicyRouteImport } from './routes/_help/privacy-policy'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiNotificationsStreamRouteImport } from './routes/api/notifications/stream'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticateduserMeRouteImport } from './routes/_authenticated/(user)/me'
import { Route as AuthenticatedsearchSearchRouteImport } from './routes/_authenticated/(search)/search'
import { Route as AuthenticatedcontactsContactsRouteImport } from './routes/_authenticated/(contacts)/contacts'
import { Route as AuthenticateduserMeIndexRouteImport } from './routes/_authenticated/(user)/me/index'
import { Route as AuthenticateduserMeSecurityRouteImport } from './routes/_authenticated/(user)/me/security'

const WhatIsIntrohubRoute = WhatIsIntrohubRouteImport.update({
  id: '/what-is-introhub',
  path: '/what-is-introhub',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GetDemoRoute = GetDemoRouteImport.update({
  id: '/get-demo',
  path: '/get-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/_help',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpTermsAndConditionsRoute = HelpTermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => HelpRoute,
} as any)
const HelpPrivacyPolicyRoute = HelpPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => HelpRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsStreamRoute = ApiNotificationsStreamRouteImport.update({
  id: '/api/notifications/stream',
  path: '/api/notifications/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticateduserMeRoute = AuthenticateduserMeRouteImport.update({
  id: '/(user)/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedsearchSearchRoute =
  AuthenticatedsearchSearchRouteImport.update({
    id: '/(search)/search',
    path: '/search',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedcontactsContactsRoute =
  AuthenticatedcontactsContactsRouteImport.update({
    id: '/(contacts)/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticateduserMeIndexRoute =
  AuthenticateduserMeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticateduserMeRoute,
  } as any)
const AuthenticateduserMeSecurityRoute =
  AuthenticateduserMeSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticateduserMeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-demo': typeof GetDemoRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/what-is-introhub': typeof WhatIsIntrohubRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/privacy-policy': typeof HelpPrivacyPolicyRoute
  '/terms-and-conditions': typeof HelpTermsAndConditionsRoute
  '/api/upload': typeof ApiUploadRoute
  '/contacts': typeof AuthenticatedcontactsContactsRoute
  '/search': typeof AuthenticatedsearchSearchRoute
  '/me': typeof AuthenticateduserMeRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/me/security': typeof AuthenticateduserMeSecurityRoute
  '/me/': typeof AuthenticateduserMeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-demo': typeof GetDemoRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/what-is-introhub': typeof WhatIsIntrohubRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/privacy-policy': typeof HelpPrivacyPolicyRoute
  '/terms-and-conditions': typeof HelpTermsAndConditionsRoute
  '/api/upload': typeof ApiUploadRoute
  '/contacts': typeof AuthenticatedcontactsContactsRoute
  '/search': typeof AuthenticatedsearchSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/me/security': typeof AuthenticateduserMeSecurityRoute
  '/me': typeof AuthenticateduserMeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_help': typeof HelpRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-demo': typeof GetDemoRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/what-is-introhub': typeof WhatIsIntrohubRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_help/privacy-policy': typeof HelpPrivacyPolicyRoute
  '/_help/terms-and-conditions': typeof HelpTermsAndConditionsRoute
  '/api/upload': typeof ApiUploadRoute
  '/_authenticated/(contacts)/contacts': typeof AuthenticatedcontactsContactsRoute
  '/_authenticated/(search)/search': typeof AuthenticatedsearchSearchRoute
  '/_authenticated/(user)/me': typeof AuthenticateduserMeRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/(user)/me/security': typeof AuthenticateduserMeSecurityRoute
  '/_authenticated/(user)/me/': typeof AuthenticateduserMeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/get-demo'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/what-is-introhub'
    | '/dashboard'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/api/upload'
    | '/contacts'
    | '/search'
    | '/me'
    | '/api/auth/$'
    | '/api/notifications/stream'
    | '/api/trpc/$'
    | '/me/security'
    | '/me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/get-demo'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/what-is-introhub'
    | '/dashboard'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/api/upload'
    | '/contacts'
    | '/search'
    | '/api/auth/$'
    | '/api/notifications/stream'
    | '/api/trpc/$'
    | '/me/security'
    | '/me'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_help'
    | '/forgot-password'
    | '/get-demo'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/what-is-introhub'
    | '/_authenticated/dashboard'
    | '/_help/privacy-policy'
    | '/_help/terms-and-conditions'
    | '/api/upload'
    | '/_authenticated/(contacts)/contacts'
    | '/_authenticated/(search)/search'
    | '/_authenticated/(user)/me'
    | '/api/auth/$'
    | '/api/notifications/stream'
    | '/api/trpc/$'
    | '/_authenticated/(user)/me/security'
    | '/_authenticated/(user)/me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HelpRoute: typeof HelpRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GetDemoRoute: typeof GetDemoRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  WhatIsIntrohubRoute: typeof WhatIsIntrohubRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNotificationsStreamRoute: typeof ApiNotificationsStreamRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-is-introhub': {
      id: '/what-is-introhub'
      path: '/what-is-introhub'
      fullPath: '/what-is-introhub'
      preLoaderRoute: typeof WhatIsIntrohubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-demo': {
      id: '/get-demo'
      path: '/get-demo'
      fullPath: '/get-demo'
      preLoaderRoute: typeof GetDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_help': {
      id: '/_help'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_help/terms-and-conditions': {
      id: '/_help/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof HelpTermsAndConditionsRouteImport
      parentRoute: typeof HelpRoute
    }
    '/_help/privacy-policy': {
      id: '/_help/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof HelpPrivacyPolicyRouteImport
      parentRoute: typeof HelpRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/stream': {
      id: '/api/notifications/stream'
      path: '/api/notifications/stream'
      fullPath: '/api/notifications/stream'
      preLoaderRoute: typeof ApiNotificationsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/(user)/me': {
      id: '/_authenticated/(user)/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticateduserMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(search)/search': {
      id: '/_authenticated/(search)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedsearchSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(contacts)/contacts': {
      id: '/_authenticated/(contacts)/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedcontactsContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(user)/me/': {
      id: '/_authenticated/(user)/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof AuthenticateduserMeIndexRouteImport
      parentRoute: typeof AuthenticateduserMeRoute
    }
    '/_authenticated/(user)/me/security': {
      id: '/_authenticated/(user)/me/security'
      path: '/security'
      fullPath: '/me/security'
      preLoaderRoute: typeof AuthenticateduserMeSecurityRouteImport
      parentRoute: typeof AuthenticateduserMeRoute
    }
  }
}

interface AuthenticateduserMeRouteChildren {
  AuthenticateduserMeSecurityRoute: typeof AuthenticateduserMeSecurityRoute
  AuthenticateduserMeIndexRoute: typeof AuthenticateduserMeIndexRoute
}

const AuthenticateduserMeRouteChildren: AuthenticateduserMeRouteChildren = {
  AuthenticateduserMeSecurityRoute: AuthenticateduserMeSecurityRoute,
  AuthenticateduserMeIndexRoute: AuthenticateduserMeIndexRoute,
}

const AuthenticateduserMeRouteWithChildren =
  AuthenticateduserMeRoute._addFileChildren(AuthenticateduserMeRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedcontactsContactsRoute: typeof AuthenticatedcontactsContactsRoute
  AuthenticatedsearchSearchRoute: typeof AuthenticatedsearchSearchRoute
  AuthenticateduserMeRoute: typeof AuthenticateduserMeRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedcontactsContactsRoute: AuthenticatedcontactsContactsRoute,
  AuthenticatedsearchSearchRoute: AuthenticatedsearchSearchRoute,
  AuthenticateduserMeRoute: AuthenticateduserMeRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface HelpRouteChildren {
  HelpPrivacyPolicyRoute: typeof HelpPrivacyPolicyRoute
  HelpTermsAndConditionsRoute: typeof HelpTermsAndConditionsRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpPrivacyPolicyRoute: HelpPrivacyPolicyRoute,
  HelpTermsAndConditionsRoute: HelpTermsAndConditionsRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HelpRoute: HelpRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GetDemoRoute: GetDemoRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  WhatIsIntrohubRoute: WhatIsIntrohubRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNotificationsStreamRoute: ApiNotificationsStreamRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
