/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as HelpRouteImport } from './routes/_help'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as PublicWhatIsIntrohubRouteImport } from './routes/_public/what-is-introhub'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicGetDemoRouteImport } from './routes/_public/get-demo'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as HelpTermsAndConditionsRouteImport } from './routes/_help/terms-and-conditions'
import { Route as HelpPrivacyPolicyRouteImport } from './routes/_help/privacy-policy'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiNotificationsStreamRouteImport } from './routes/api/notifications/stream'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticateduserMeRouteImport } from './routes/_authenticated/(user)/me'
import { Route as AuthenticatedsearchSearchRouteImport } from './routes/_authenticated/(search)/search'
import { Route as AuthenticatedrequestsRequestsRouteImport } from './routes/_authenticated/(requests)/requests'
import { Route as AuthenticateddashboardDashboardRouteImport } from './routes/_authenticated/(dashboard)/dashboard'
import { Route as AuthenticatedcontactsContactsRouteImport } from './routes/_authenticated/(contacts)/contacts'
import { Route as AuthenticateduserMeIndexRouteImport } from './routes/_authenticated/(user)/me/index'
import { Route as AuthenticateduserMeSecurityRouteImport } from './routes/_authenticated/(user)/me/security'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/_help',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicWhatIsIntrohubRoute = PublicWhatIsIntrohubRouteImport.update({
  id: '/what-is-introhub',
  path: '/what-is-introhub',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGetDemoRoute = PublicGetDemoRouteImport.update({
  id: '/get-demo',
  path: '/get-demo',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const HelpTermsAndConditionsRoute = HelpTermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => HelpRoute,
} as any)
const HelpPrivacyPolicyRoute = HelpPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => HelpRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsStreamRoute = ApiNotificationsStreamRouteImport.update({
  id: '/api/notifications/stream',
  path: '/api/notifications/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticateduserMeRoute = AuthenticateduserMeRouteImport.update({
  id: '/(user)/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedsearchSearchRoute =
  AuthenticatedsearchSearchRouteImport.update({
    id: '/(search)/search',
    path: '/search',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedrequestsRequestsRoute =
  AuthenticatedrequestsRequestsRouteImport.update({
    id: '/(requests)/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticateddashboardDashboardRoute =
  AuthenticateddashboardDashboardRouteImport.update({
    id: '/(dashboard)/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedcontactsContactsRoute =
  AuthenticatedcontactsContactsRouteImport.update({
    id: '/(contacts)/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticateduserMeIndexRoute =
  AuthenticateduserMeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticateduserMeRoute,
  } as any)
const AuthenticateduserMeSecurityRoute =
  AuthenticateduserMeSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticateduserMeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/privacy-policy': typeof HelpPrivacyPolicyRoute
  '/terms-and-conditions': typeof HelpTermsAndConditionsRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/get-demo': typeof PublicGetDemoRoute
  '/login': typeof PublicLoginRoute
  '/pricing': typeof PublicPricingRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/signup': typeof PublicSignupRoute
  '/what-is-introhub': typeof PublicWhatIsIntrohubRoute
  '/api/upload': typeof ApiUploadRoute
  '/contacts': typeof AuthenticatedcontactsContactsRoute
  '/dashboard': typeof AuthenticateddashboardDashboardRoute
  '/requests': typeof AuthenticatedrequestsRequestsRoute
  '/search': typeof AuthenticatedsearchSearchRoute
  '/me': typeof AuthenticateduserMeRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/me/security': typeof AuthenticateduserMeSecurityRoute
  '/me/': typeof AuthenticateduserMeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/privacy-policy': typeof HelpPrivacyPolicyRoute
  '/terms-and-conditions': typeof HelpTermsAndConditionsRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/get-demo': typeof PublicGetDemoRoute
  '/login': typeof PublicLoginRoute
  '/pricing': typeof PublicPricingRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/signup': typeof PublicSignupRoute
  '/what-is-introhub': typeof PublicWhatIsIntrohubRoute
  '/api/upload': typeof ApiUploadRoute
  '/contacts': typeof AuthenticatedcontactsContactsRoute
  '/dashboard': typeof AuthenticateddashboardDashboardRoute
  '/requests': typeof AuthenticatedrequestsRequestsRoute
  '/search': typeof AuthenticatedsearchSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/me/security': typeof AuthenticateduserMeSecurityRoute
  '/me': typeof AuthenticateduserMeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_help': typeof HelpRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_help/privacy-policy': typeof HelpPrivacyPolicyRoute
  '/_help/terms-and-conditions': typeof HelpTermsAndConditionsRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/get-demo': typeof PublicGetDemoRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_public/what-is-introhub': typeof PublicWhatIsIntrohubRoute
  '/api/upload': typeof ApiUploadRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/(contacts)/contacts': typeof AuthenticatedcontactsContactsRoute
  '/_authenticated/(dashboard)/dashboard': typeof AuthenticateddashboardDashboardRoute
  '/_authenticated/(requests)/requests': typeof AuthenticatedrequestsRequestsRoute
  '/_authenticated/(search)/search': typeof AuthenticatedsearchSearchRoute
  '/_authenticated/(user)/me': typeof AuthenticateduserMeRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/(user)/me/security': typeof AuthenticateduserMeSecurityRoute
  '/_authenticated/(user)/me/': typeof AuthenticateduserMeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/forgot-password'
    | '/get-demo'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/what-is-introhub'
    | '/api/upload'
    | '/contacts'
    | '/dashboard'
    | '/requests'
    | '/search'
    | '/me'
    | '/api/auth/$'
    | '/api/notifications/stream'
    | '/api/trpc/$'
    | '/me/security'
    | '/me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/forgot-password'
    | '/get-demo'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/what-is-introhub'
    | '/api/upload'
    | '/contacts'
    | '/dashboard'
    | '/requests'
    | '/search'
    | '/api/auth/$'
    | '/api/notifications/stream'
    | '/api/trpc/$'
    | '/me/security'
    | '/me'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_help'
    | '/_public'
    | '/_help/privacy-policy'
    | '/_help/terms-and-conditions'
    | '/_public/forgot-password'
    | '/_public/get-demo'
    | '/_public/login'
    | '/_public/pricing'
    | '/_public/reset-password'
    | '/_public/signup'
    | '/_public/what-is-introhub'
    | '/api/upload'
    | '/_public/'
    | '/_authenticated/(contacts)/contacts'
    | '/_authenticated/(dashboard)/dashboard'
    | '/_authenticated/(requests)/requests'
    | '/_authenticated/(search)/search'
    | '/_authenticated/(user)/me'
    | '/api/auth/$'
    | '/api/notifications/stream'
    | '/api/trpc/$'
    | '/_authenticated/(user)/me/security'
    | '/_authenticated/(user)/me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HelpRoute: typeof HelpRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNotificationsStreamRoute: typeof ApiNotificationsStreamRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_help': {
      id: '/_help'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/what-is-introhub': {
      id: '/_public/what-is-introhub'
      path: '/what-is-introhub'
      fullPath: '/what-is-introhub'
      preLoaderRoute: typeof PublicWhatIsIntrohubRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/get-demo': {
      id: '/_public/get-demo'
      path: '/get-demo'
      fullPath: '/get-demo'
      preLoaderRoute: typeof PublicGetDemoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_help/terms-and-conditions': {
      id: '/_help/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof HelpTermsAndConditionsRouteImport
      parentRoute: typeof HelpRoute
    }
    '/_help/privacy-policy': {
      id: '/_help/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof HelpPrivacyPolicyRouteImport
      parentRoute: typeof HelpRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/stream': {
      id: '/api/notifications/stream'
      path: '/api/notifications/stream'
      fullPath: '/api/notifications/stream'
      preLoaderRoute: typeof ApiNotificationsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/(user)/me': {
      id: '/_authenticated/(user)/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticateduserMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(search)/search': {
      id: '/_authenticated/(search)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedsearchSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(requests)/requests': {
      id: '/_authenticated/(requests)/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedrequestsRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(dashboard)/dashboard': {
      id: '/_authenticated/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticateddashboardDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(contacts)/contacts': {
      id: '/_authenticated/(contacts)/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedcontactsContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(user)/me/': {
      id: '/_authenticated/(user)/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof AuthenticateduserMeIndexRouteImport
      parentRoute: typeof AuthenticateduserMeRoute
    }
    '/_authenticated/(user)/me/security': {
      id: '/_authenticated/(user)/me/security'
      path: '/security'
      fullPath: '/me/security'
      preLoaderRoute: typeof AuthenticateduserMeSecurityRouteImport
      parentRoute: typeof AuthenticateduserMeRoute
    }
  }
}

interface AuthenticateduserMeRouteChildren {
  AuthenticateduserMeSecurityRoute: typeof AuthenticateduserMeSecurityRoute
  AuthenticateduserMeIndexRoute: typeof AuthenticateduserMeIndexRoute
}

const AuthenticateduserMeRouteChildren: AuthenticateduserMeRouteChildren = {
  AuthenticateduserMeSecurityRoute: AuthenticateduserMeSecurityRoute,
  AuthenticateduserMeIndexRoute: AuthenticateduserMeIndexRoute,
}

const AuthenticateduserMeRouteWithChildren =
  AuthenticateduserMeRoute._addFileChildren(AuthenticateduserMeRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedcontactsContactsRoute: typeof AuthenticatedcontactsContactsRoute
  AuthenticateddashboardDashboardRoute: typeof AuthenticateddashboardDashboardRoute
  AuthenticatedrequestsRequestsRoute: typeof AuthenticatedrequestsRequestsRoute
  AuthenticatedsearchSearchRoute: typeof AuthenticatedsearchSearchRoute
  AuthenticateduserMeRoute: typeof AuthenticateduserMeRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedcontactsContactsRoute: AuthenticatedcontactsContactsRoute,
  AuthenticateddashboardDashboardRoute: AuthenticateddashboardDashboardRoute,
  AuthenticatedrequestsRequestsRoute: AuthenticatedrequestsRequestsRoute,
  AuthenticatedsearchSearchRoute: AuthenticatedsearchSearchRoute,
  AuthenticateduserMeRoute: AuthenticateduserMeRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface HelpRouteChildren {
  HelpPrivacyPolicyRoute: typeof HelpPrivacyPolicyRoute
  HelpTermsAndConditionsRoute: typeof HelpTermsAndConditionsRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpPrivacyPolicyRoute: HelpPrivacyPolicyRoute,
  HelpTermsAndConditionsRoute: HelpTermsAndConditionsRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicGetDemoRoute: typeof PublicGetDemoRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicSignupRoute: typeof PublicSignupRoute
  PublicWhatIsIntrohubRoute: typeof PublicWhatIsIntrohubRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicGetDemoRoute: PublicGetDemoRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicSignupRoute: PublicSignupRoute,
  PublicWhatIsIntrohubRoute: PublicWhatIsIntrohubRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HelpRoute: HelpRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNotificationsStreamRoute: ApiNotificationsStreamRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
